package instantvas.smsengine.producersandconsumers;

import config.InstantVASApplicationConfiguration;
import instantvas.smsengine.InstantVASHTTPInstrumentationRequestProperty;
import mutua.events.EventClient;
import mutua.events.IEventLink;
import mutua.icc.instrumentation.Instrumentation;
import mutua.smsappmodule.smslogic.SMSAppModuleCommandsSubscription;

/** <pre>
 * SRConsumer.java
 * ===============
 * (created by luiz, Mar 16, 2016)
 *
 * Processes "Subscription Renewal" events generated by {@link SRProducer}, transmitted via an instance of {@link IEventLink}. 
 *
 * @version $Id$
 * @author luiz
*/

public class SRConsumer implements EventClient<EInstantVASEvents> {
	
	private Instrumentation<InstantVASHTTPInstrumentationRequestProperty, String> log;
	private SMSAppModuleCommandsSubscription subscriptionCommands;
	
	public SRConsumer(InstantVASApplicationConfiguration ivac) {
		log  = ivac.log;
		subscriptionCommands = ivac.subscriptionCommands;
	}
	
	@InstantVASEvent(EInstantVASEvents.SUBSCRIPTION_RENEWED)
	public void assureMSISDNIsSubscribed(String msisdn) {
		try {
			log.reportRequestStart("Assuring MSISDN '"+msisdn+"' is a Subscriber");
			subscriptionCommands.subscribeUser(msisdn);
		} catch (Throwable t) {
			log.reportThrowable(t, "Error while assuring MSISDN '"+msisdn+"' is subscribed");
		} finally {
			log.reportRequestFinish();
		}
	}
}